const mongoose = require('mongoose');
const Task = require('../models/Task');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../../.env') });

const seedTasks = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('Connected to DB for seeding tasks...');

        await Task.deleteMany({});

        const tasks = [
            // ========== DAILY MISSIONS (10) ==========
            {
                title: { en: 'Morning Hydration', es: 'Hidratación Matutina' },
                description: { en: 'Drink a glass of water when you wake up', es: 'Bebe un vaso de agua al despertar' },
                category: 'Health & Fitness',
                rewardXP: 20,
                rewardGold: 30,
                repeatType: 'daily',
                type: 'system',
                difficulty: 1,
            },
            {
                title: { en: 'Exercise 30 Minutes', es: 'Ejercicio 30 Minutos' },
                description: { en: 'Do any physical activity for 30 minutes', es: 'Realiza cualquier actividad física durante 30 minutos' },
                category: 'Health & Fitness',
                rewardXP: 50,
                rewardGold: 100,
                repeatType: 'daily',
                type: 'system',
                difficulty: 2,
            },
            {
                title: { en: 'Healthy Breakfast', es: 'Desayuno Saludable' },
                description: { en: 'Eat a nutritious breakfast', es: 'Come un desayuno nutritivo' },
                category: 'Health & Fitness',
                rewardXP: 30,
                rewardGold: 50,
                repeatType: 'daily',
                type: 'system',
                difficulty: 1,
            },
            {
                title: { en: 'Stretching Routine', es: 'Rutina de Estiramiento' },
                description: { en: 'Spend 10 minutes stretching your body', es: 'Dedica 10 minutos a estirar tu cuerpo' },
                category: 'Health & Fitness',
                rewardXP: 25,
                rewardGold: 40,
                repeatType: 'daily',
                type: 'system',
                difficulty: 1,
            },
            {
                title: { en: 'Sugar Free Day', es: 'Día Sin Azúcar' },
                description: { en: 'Avoid added sugars for the entire day', es: 'Evita azúcares añadidos durante todo el día' },
                category: 'Health & Fitness',
                rewardXP: 60,
                rewardGold: 90,
                repeatType: 'daily',
                type: 'system',
                difficulty: 3,
            },
            {
                title: { en: 'Read 20 Pages', es: 'Leer 20 Páginas' },
                description: { en: 'Read at least 20 pages of a book', es: 'Lee al menos 20 páginas de un libro' },
                category: 'Mental Wellbeing',
                rewardXP: 40,
                rewardGold: 75,
                repeatType: 'daily',
                type: 'system',
                difficulty: 2,
            },
            {
                title: { en: 'Meditation', es: 'Meditación' },
                description: { en: 'Meditate for 10 minutes', es: 'Medita durante 10 minutos' },
                category: 'Mental Wellbeing',
                rewardXP: 35,
                rewardGold: 60,
                repeatType: 'daily',
                type: 'system',
                difficulty: 2,
            },
            {
                title: { en: 'Journaling', es: 'Diario Personal' },
                description: { en: 'Write down your thoughts or gratitude for the day', es: 'Escribe tus pensamientos o gratitud del día' },
                category: 'Mental Wellbeing',
                rewardXP: 30,
                rewardGold: 50,
                repeatType: 'daily',
                type: 'system',
                difficulty: 1,
            },
            {
                title: { en: 'Learn Something New', es: 'Aprender Algo Nuevo' },
                description: { en: 'Spend 30 minutes learning a new skill', es: 'Dedica 30 minutos a aprender una nueva habilidad' },
                category: 'Mental Wellbeing',
                rewardXP: 45,
                rewardGold: 80,
                repeatType: 'daily',
                type: 'system',
                difficulty: 2,
            },
            {
                title: { en: 'Social Connection', es: 'Conexión Social' },
                description: { en: 'Have a meaningful conversation with someone', es: 'Ten una conversación significativa con alguien' },
                category: 'Social',
                rewardXP: 35,
                rewardGold: 60,
                repeatType: 'daily',
                type: 'system',
                difficulty: 2,
            },
            {
                title: { en: 'Call a Friend', es: 'Llamar a un Amigo' },
                description: { en: 'Call a friend or family member just to chat', es: 'Llama a un amigo o familiar solo para charlar' },
                category: 'Social',
                rewardXP: 40,
                rewardGold: 70,
                repeatType: 'daily',
                type: 'system',
                difficulty: 2,
            },
            {
                title: { en: 'Clean Your Space', es: 'Limpia Tu Espacio' },
                description: { en: 'Organize and clean your room or workspace', es: 'Organiza y limpia tu habitación o espacio de trabajo' },
                category: 'Productivity',
                rewardXP: 40,
                rewardGold: 75,
                repeatType: 'daily',
                type: 'system',
                difficulty: 2,
            },
            {
                title: { en: 'Plan Tomorrow', es: 'Planificar Mañana' },
                description: { en: 'Write down your top 3 goals for tomorrow', es: 'Escribe tus 3 objetivos principales para mañana' },
                category: 'Productivity',
                rewardXP: 25,
                rewardGold: 40,
                repeatType: 'daily',
                type: 'system',
                difficulty: 1,
            },
            {
                title: { en: 'Deep Work Session', es: 'Sesión de Trabajo Profundo' },
                description: { en: 'Work for 60 minutes without distractions', es: 'Trabaja durante 60 minutos sin distracciones' },
                category: 'Productivity',
                rewardXP: 60,
                rewardGold: 100,
                repeatType: 'daily',
                type: 'system',
                difficulty: 3,
            },
            {
                title: { en: 'Creative Sketch', es: 'Boceto Creativo' },
                description: { en: 'Spend 15 minutes drawing or doodling', es: 'Dedica 15 minutos a dibujar o hacer garabatos' },
                category: 'Creativity',
                rewardXP: 30,
                rewardGold: 50,
                repeatType: 'daily',
                type: 'system',
                difficulty: 1,
            },

            // ========== WEEKLY MISSIONS (10) ==========
            {
                title: { en: 'Exercise 5 Days', es: 'Ejercicio 5 Días' },
                description: { en: 'Exercise at least 5 days this week', es: 'Haz ejercicio al menos 5 días esta semana' },
                category: 'Health & Fitness',
                rewardXP: 200,
                rewardGold: 400,
                repeatType: 'weekly',
                type: 'system',
                difficulty: 3,
            },
            {
                title: { en: 'Run 10km Total', es: 'Correr 10km Total' },
                description: { en: 'Accumulate 10km of running or walking this week', es: 'Acumula 10km corriendo o caminando esta semana' },
                category: 'Health & Fitness',
                rewardXP: 250,
                rewardGold: 450,
                repeatType: 'weekly',
                type: 'system',
                difficulty: 3,
            },
            {
                title: { en: 'Read a Book', es: 'Leer un Libro' },
                description: { en: 'Finish reading a book', es: 'Termina de leer un libro' },
                category: 'Mental Wellbeing',
                rewardXP: 300,
                rewardGold: 550,
                repeatType: 'weekly',
                type: 'system',
                difficulty: 4,
            },
            {
                title: { en: 'Learn New Recipe', es: 'Aprender Nueva Receta' },
                description: { en: 'Cook a new healthy recipe', es: 'Cocina una nueva receta saludable' },
                category: 'Health & Fitness',
                rewardXP: 180,
                rewardGold: 350,
                repeatType: 'weekly',
                type: 'system',
                difficulty: 3,
            },
            {
                title: { en: 'Volunteer Work', es: 'Trabajo Voluntario' },
                description: { en: 'Help someone or do volunteer work', es: 'Ayuda a alguien o haz trabajo voluntario' },
                category: 'Social',
                rewardXP: 400,
                rewardGold: 800,
                repeatType: 'weekly',
                type: 'system',
                difficulty: 4,
            },
            {
                title: { en: 'Host a Game Night', es: 'Noche de Juegos' },
                description: { en: 'Organize a game night with friends or family', es: 'Organiza una noche de juegos con amigos o familia' },
                category: 'Social',
                rewardXP: 250,
                rewardGold: 450,
                repeatType: 'weekly',
                type: 'system',
                difficulty: 3,
            },
            {
                title: { en: 'Creative Project', es: 'Proyecto Creativo' },
                description: { en: 'Work on a creative project for 3 hours', es: 'Trabaja en un proyecto creativo durante 3 horas' },
                category: 'Creativity',
                rewardXP: 220,
                rewardGold: 450,
                repeatType: 'weekly',
                type: 'system',
                difficulty: 3,
            },
            {
                title: { en: 'Nature Hike', es: 'Caminata en la Naturaleza' },
                description: { en: 'Go for a long hike in nature', es: 'Ve a una caminata larga en la naturaleza' },
                category: 'Health & Fitness',
                rewardXP: 200,
                rewardGold: 380,
                repeatType: 'weekly',
                type: 'system',
                difficulty: 2,
            },
            {
                title: { en: 'Zero Inbox', es: 'Bandeja de Entrada Cero' },
                description: { en: 'Clear your email inbox completely', es: 'Limpia tu bandeja de entrada de correo completamente' },
                category: 'Productivity',
                rewardXP: 150,
                rewardGold: 300,
                repeatType: 'weekly',
                type: 'system',
                difficulty: 2,
            },
            {
                title: { en: 'Budget Review', es: 'Revisión de Presupuesto' },
                description: { en: 'Review your weekly expenses and budget', es: 'Revisa tus gastos semanales y presupuesto' },
                category: 'Productivity',
                rewardXP: 160,
                rewardGold: 320,
                repeatType: 'weekly',
                type: 'system',
                difficulty: 2,
            },
            {
                title: { en: 'Fix Something', es: 'Reparar Algo' },
                description: { en: 'Repair something broken in your house', es: 'Repara algo roto en tu casa' },
                category: 'Productivity',
                rewardXP: 180,
                rewardGold: 350,
                repeatType: 'weekly',
                type: 'system',
                difficulty: 3,
            },
        ];

        await Task.insertMany(tasks);
        console.log('Tasks seeded successfully');
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedTasks();
